### ISSUE TITLE
autocomplete-java-minus

### ISSUE THREAD

**Issue by rishabh8** [noseglid/autocomplete-java-minus#9] opened 2016-08-29 12:39 UTC
This package throw an exception to install. There is output 

oniguruma@6.1.0 install C:\Users\Rishabh\AppData\Local\Temp\apm-install-dir-116729-2148-eshbig\node_modules\autocomplete-java-minus\node_modules\first-mate\node_modules\oniguruma

> node-gyp rebuild

C:\Users\Rishabh\AppData\Local\Temp\apm-install-dir-116729-2148-eshbig\node_modules\autocomplete-java-minus\node_modules\first-mate\node_modules\oniguruma>if not defined npm_config_node_gyp (node "C:\Users\Rishabh\AppData\Local\atom\app-1.9.9\resources\app\apm\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

npm WARN engine sb-exec@3.0.1: wanted: {"node":">=6.0.0"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\Users\Rishabh\AppData\Local\atom\app-1.9.9\resources\app\apm\bin\node.exe" "C:\Users\Rishabh\AppData\Local\atom\app-1.9.9\resources\app\apm\node_modules\npm\bin\npm-cli.js" "--globalconfig" "C:\Users\Rishabh\.atom\.apm\.apmrc" "--userconfig" "C:\Users\Rishabh\.atom\.apmrc" "install" "C:\Users\Rishabh\AppData\Local\Temp\d-116729-2148-1jc10qo\package.tgz" "--target=0.37.8" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR! 
npm ERR! Failed at the oniguruma@6.1.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

**Comment by noseglid** [comment] 2016-08-29 13:19
dupe of #8

**Closed as completed by noseglid** 2016-08-29 13:19 UTC
